### ISSUE TITLE
Kommentare importieren

### ISSUE THREAD

**Issue by davidak** [davidak/davidak.de#7]
- [x] [Isso](https://posativ.org/isso/) testweise aufsetzen
- [x] Kommentare aus Wordpress importieren

```
nix-env -iA isso -f /root/nixpkgs/
isso -c /nix/store/7avrwr93i1zg7sip2bb8vb50csx6vlvi-isso.cfg import nixos/davidakweblog.wordpress.2016-03-05.xml
[100%]  249 threads, 830 comments
```

**Comment by davidak** [comment]
waiting for isso module land in NixOS. (https://github.com/NixOS/nixpkgs/pull/13587)

**Comment by Profpatsch** [comment]
You can use the module right now, by patching the PR into your server configuration if you want to. For the service user & group id just use some number that won’t be reached by nixpkgs in a while (e.g. 500).

**Comment by davidak** [comment]
Also check out https://docs.commento.io/installation/self-hosting/

**Comment by davidak** [comment]
Kommentare sollen in der statischen Webseite enthalten sein und somit archiviert werden. Dafür müssen sie beim Bauen der Seite geladen werden können. Es macht Sinn sie als strukturierte Daten zu behalten, um später anderweitig verwendet werden zu können. Also nicht einfach als Markdown. Sie könne z.B. als YAML im Frontmatter hinzugefügt werden.

Es ist gut, wenn Kommentatoren noch einige Zeit haben ihren Kommentar zu editieren (z.B. 15 Minuten).

UP/Down Voting ist auch ein hilfreiches Feature, um sinnvolle Kommentare hervorzuheben. Funktioniert aber nur mit einer Datenbank. Bei der geringen Anzahl von Kommentaren auf meiner Webseite weniger wichtig.

Eventuell vorhandene Kommentare in der Seite haben und zusätzliche Daten aus Backend laden?

https://darekkay.com/blog/static-site-comments/
https://gohugo.io/content-management/comments/
https://www.getshifter.io/static-site-comments/
https://blog.joeldare.com/how-i-implemented-comments-on-a-static-site/

https://indieweb.org/comments

**Comment by davidak** [comment]
New plan: https://pad.nixnet.services/U0RU2OpgTbqHMoXnZKHZZw
